set_property PACKAGE_PIN W5 [ get_ports clk_w5]
set_property IOSTANDARD LVCMOS33 [ get_ports clk_w5]
create_clock -add -name sys_clk_pin  -period 10.00  -waveform {0 5}{get_ports clk_w5}

set_property PACKAGE_PIN U18 [get_ports btc]
set_property IOSTANDARD LVCMOS33 [get_ports btc]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btc]

set_property PACKAGE_PIN W19 [get_ports btl]
set_property IOSTANDARD LVCMOS33 [get_ports btl]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btl]

set_property PACKAGE_PIN W4 [ get_ports s[0]]
set_property IOSTANDARD LVCMOS33 [ get_ports s[0]]
set_property PACKAGE_PIN V4 [ get_ports s[1]]
set_property IOSTANDARD LVCMOS33 [ get_ports s[1]]
set_property PACKAGE_PIN U4 [ get_ports s[2]]
set_property IOSTANDARD LVCMOS33 [ get_ports s[2]]
set_property PACKAGE_PIN U2 [ get_ports s[3]]
set_property IOSTANDARD LVCMOS33 [ get_ports s[3]]

set_property PACKAGE_PIN W7 [ get_ports q[0]]
set_property IOSTANDARD LVCMOS33 [ get_ports q[0]]
set_property PACKAGE_PIN W6 [ get_ports q[1]]
set_property IOSTANDARD LVCMOS33 [ get_ports q[1]]
set_property PACKAGE_PIN U8 [ get_ports q[2]]
set_property IOSTANDARD LVCMOS33 [ get_ports q[2]]
set_property PACKAGE_PIN V8 [ get_ports q[3]]
set_property IOSTANDARD LVCMOS33 [ get_ports q[3]]
set_property PACKAGE_PIN U5 [ get_ports q[4]]
set_property IOSTANDARD LVCMOS33 [ get_ports q[4]]
set_property PACKAGE_PIN V5 [ get_ports q[5]]
set_property IOSTANDARD LVCMOS33 [ get_ports q[5]]
set_property PACKAGE_PIN U7 [ get_ports q[6]]
set_property IOSTANDARD LVCMOS33 [ get_ports q[6]]
set_property PACKAGE_PIN V7 [ get_ports q[7]]
set_property IOSTANDARD LVCMOS33 [ get_ports q[7]]

set_property PACKAGE_PIN U16 [ get_ports w[0]]
set_property IOSTANDARD LVCMOS33 [ get_ports w[0]]
set_property PACKAGE_PIN E19 [ get_ports w[1]]
set_property IOSTANDARD LVCMOS33 [ get_ports w[1]]
set_property PACKAGE_PIN U19 [ get_ports w[2]]
set_property IOSTANDARD LVCMOS33 [ get_ports w[2]]
set_property PACKAGE_PIN V19 [ get_ports w[3]]
set_property IOSTANDARD LVCMOS33 [ get_ports  w[3]]
set_property PACKAGE_PIN W18 [ get_ports  w[4]]
set_property IOSTANDARD LVCMOS33 [ get_ports  w[4]]
set_property PACKAGE_PIN U15 [ get_ports w[5]]
set_property IOSTANDARD LVCMOS33 [ get_ports w[5]]
set_property PACKAGE_PIN U14 [ get_ports  w[6]]
set_property IOSTANDARD LVCMOS33 [ get_ports  w[6]]
set_property PACKAGE_PIN V14 [ get_ports  w[7]]
set_property IOSTANDARD LVCMOS33 [ get_ports  w[7]]
set_property PACKAGE_PIN V13 [ get_ports  w[8]]
set_property IOSTANDARD LVCMOS33 [ get_ports  w[8]]
set_property PACKAGE_PIN V3 [ get_ports w[9]]
set_property IOSTANDARD LVCMOS33 [ get_ports  w[9]]
set_property PACKAGE_PIN W3 [ get_ports  w[10]]
set_property IOSTANDARD LVCMOS33 [ get_ports  w[10]]
set_property PACKAGE_PIN U3 [ get_ports  w[11]]
set_property IOSTANDARD LVCMOS33 [ get_ports  w[11]]
set_property PACKAGE_PIN P3 [ get_ports w[12]]
set_property IOSTANDARD LVCMOS33 [ get_ports w[12]]
set_property PACKAGE_PIN N3 [ get_ports w[13]]
set_property IOSTANDARD LVCMOS33 [ get_ports w[13]]
set_property PACKAGE_PIN P1 [ get_ports w[14]]
set_property IOSTANDARD LVCMOS33 [ get_ports w[14]]
set_property PACKAGE_PIN L1 [ get_ports w[15]]
set_property IOSTANDARD LVCMOS33 [ get_ports w[15]]
